      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/danish-co/ci-cd-test-api:${{ github.sha }}

            docker stop ci-cd-test-api || true
            docker rm ci-cd-test-api || true

            docker run -d \
              --name ci-cd-test-api \
              --restart unless-stopped \
              -p 9000:9000 \
              ghcr.io/danish-co/ci-cd-test-api:${{ github.sha }}

            docker image prune -f